
#       Dependencias
FROM node:22.14-alpine3.20 as deps

WORKDIR /usr/src/app

COPY package*.json ./
COPY package-lock.json ./

RUN npm install




#       Builder de la App
FROM node:22.14-alpine3.20 as build

WORKDIR /usr/src/app

# Copiar de deps, los módulos de node
COPY --from=deps /usr/src/app/node_modules ./node_modules 

#Copiar todo el código fuente de la aplicación omitiendo lo de dockerignore
COPY . .

RUN npm run build

RUN npm ci -f --only=production && npm cache clean --force


#       Crear Imagen final de Docker
FROM node:22.14-alpine3.20 as prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules 

#Copiar la carpeta de destino
COPY --from=build /usr/src/app/dist ./dist

ENV NODE_ENV=production

USER node

EXPOSE 3000

CMD [ "node", "dist/main.js" ]